### ISSUE TITLE
RDM shows bolt emoji but System Preferences doesn't show HiDPi

### ISSUE THREAD

**Issue by Datta0** [BetaBen1/A-Guide-to-MacOS-Scaled-Resolutions#1]
Hi, 
Thanks for the detailed guide to start with. I followed all the steps as mentioned.
I'm on Big Sur 11.2 with a Dell monitor. I couldn't mount /System as writable because of Big Sur Security. 
I instead placed the necessary files in /Library instead of /System/Library.

RDM  app shows thunderbolt icon next to 1920*1080, but that isn't selected as default. I tried selecting the one with thunderbolt icon but it still stays on the normal one (PFA Screenshot).

This is a 1920*1080 monitor and I added 3240*2160 in the file (PFA text form of the same and also screenshot).
[DisplayProductID-f09e.txt](https://github.com/bbhardin/A-Guide-to-MacOS-Scaled-Resolutions/files/5993751/DisplayProductID-f09e.txt)

![Screenshot 2021-02-17 at 12 21 21 PM](https://user-images.githubusercontent.com/39181234/108166775-ab2eee00-711a-11eb-931a-c69728ab5b47.png)

![Screenshot 2021-02-17 at 12 05 34 PM](https://user-images.githubusercontent.com/39181234/108166400-2512a780-711a-11eb-9721-d63e7aaf41fa.png)

**Comment by bbhardin** [comment]
Thanks for the detailed description and the screenshots. I have had issues with RDM that you need to select the resolution for the external display and not the internal. Or maybe it's vice versa. I assume that you've tried setting the resolution in RDM for both Display 1 and for Display 2?

I have not tried this since upgrading to Big Sur so I didn't notice the system folder write changes. Where did you place the file under /Library? In the Displays folder? For me, that folder only has color profiles. However, the fact that the created resolutions show up in RDM seems to say you placed it in the right spot. Something else to check: Does your mac have a T2 security chip? You may need to modify the permissions associated with that in order to place it under the System folder (assuming that's still possible in Big Sur). I haven't connected to a monitor since upgrading to Big Sur, but I'll try this on my system in the next day or two and see if I have any issues.

**Comment by Datta0** [comment]
Hi, sorry for the delay in response.
I  actually forgot about the same for a few days.

Now when I open RDM and see, I can enable the required resolution with bolt icon 
<img width="179" alt="Screenshot 2021-02-22 at 5 25 30 PM" src="https://user-images.githubusercontent.com/39181234/108705357-36e9b580-7533-11eb-97bc-1bd07be3a945.png">

I have no idea how this fixed itself. Maybe due to a couple of reboots I guess.

But still system preferences show HiDPi only for half the original resolution. Is this something I need to worry about?
<img width="664" alt="Screenshot 2021-02-22 at 5 29 02 PM" src="https://user-images.githubusercontent.com/39181234/108705529-757f7000-7533-11eb-92c6-aea84faca60a.png">

I placed the files in `/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-10ac`

Also, I don't have an M2 chip. I'm on a hackitosh.

**Comment by bbhardin** [comment]
Apologies for the very late response. I'm glad it's working now! If you hold the option key while pressing the Scaled option in System Preferences, does it show all of the resolutions then? I will include in my write up that holding the option key shows more scaled options. Either way, it's not something to worry about as long as RDM works.
