### ISSUE TITLE
Permission denied on Big Sur

### ISSUE THREAD

**Issue by sryze** [BetaBen1/A-Guide-to-MacOS-Scaled-Resolutions#2]
When trying to mount `/` as writeable in step 1 I this error on Big Sur 11.2.2:

```
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
```

Do you know how to fix it?

I have disabled the SIP and `csrutil status` reports that it's disabled. 

P.S. did you have any luck with adding custom scaled resolutions on for a MacBook's built-in display? I'd like to have a resolution between Larger Text (1024x640) and 1280x800 (looks like it will be 1152x720), not sure if it's possible to achieve with this method...

**Comment by bbhardin** [comment]
The process for unlocking the disk has changed in Big Sur, and I haven't had a chance to update this writeup. I haven't tried it yet, but other users have reported that the plist file can be put in /Library instead of /System/Library to fix this. I will try to try to test this and update the write up in the next few days.

I believe this method also worked with the built in MacBook display for me.

**Comment by heyhtehreh** [comment]
> The process for unlocking the disk has changed in Big Sur, and I haven't had a chance to update this writeup. I haven't tried it yet, but other users have reported that the plist file can be put in /Library instead of /System/Library to fix this. I will try to try to test this and update the write up in the next few days.
> 
> I believe this method also worked with the built in MacBook display for me.

How did it go?

**Comment by bbhardin** [comment]
Well this is embarrassing that it took so long to actually try this and get this working, but putting the file under /Library worked perfectly on Big Sur. Guide has been updated to reflect this and more changes to the guide are coming soon to make the process easier.
